BEGIN;
CREATE UNIQUE INDEX idx_Tags_tagName_unique ON "Tags" ("tagName"); -- Adding a unique index for ON CONFLICT sentence to work

INSERT INTO
    "Tags" ("tagName")
VALUES
    ('Angular'),
    ('C'),
    ('C++'),
    ('C#'),
    ('Data Science'),
    ('Deep Learning'),
    ('Express'),
    ('GraphQL'),
    ('HTML/CSS'),
    ('Inteligencia Artificial'),
    ('Java'),
    ('JavaScript'),
    ('Kotlin'),
    ('Machine Learning'),
    ('MongoDB'),
    ('MySQL'),
    ('Node.js'),
    ('PHP'),
    ('PostgreSQL'),
    ('Python'),
    ('React'),
    ('Ruby'),
    ('Rust'),
    ('SQL'),
    ('Svelte'),
    ('Swift'),
    ('Flutter:'),
    ('Larabel:'),
    ('TypeScript'),
    ('Vue'),
    ('Duda sobre la carrera'),
    ('Error de sintaxis'),
    ('Depuración'),
    ('Rendimiento'),
    ('Algoritmo'),
    ('Lógica de programación'),
    ('Optimización'),
    ('Compatibilidad'),
    ('Documentación'),
    ('General'),
    ('Administración de Bases de Datos'),
    ('Administración de Proyectos I'),
    ('Administración de Proyectos II'),
    ('Administración de Redes'),
    ('Algoritmos y Complejidad'),
    ('Análisis Numérico'),
    ('Anonimato y Privacidad'),
    ('Aplicaciones Web Escalables'),
    ('Aplicaciones Web Interactivas'),
    ('Aprendizaje Automático'),
    ('Arquitectura de Computadoras'),
    ('Arquitectura de Nube'),
    ('Arte Conceptual para Videojuegos'),
    ('Automatización'),
    ('Bases de Datos'),
    ('Bases de Datos Geoespaciales'),
    ('Ciencia de Datos'),
    ('Computación y Sociedad'),
    ('Cómputo Bio-Inspirado'),
    ('Control Digital'),
    ('Criptografía'),
    ('Diseño de Interfaces'),
    ('Diseño de Juegos'),
    ('Diseño de Microcomputadoras'),
    ('Diseño Digital'),
    ('Diseño e Implementación de Redes'),
    ('Dispositivos Semiconductores'),
    ('Estructuras de Datos Avanzadas'),
    ('Estructuras de Datos I'),
    ('Estructuras de Datos II'),
    ('Fundamentos de Circuitos Eléctricos'),
    ('Fundamentos de Compiladores'),
    ('Fundamentos de Desarrollo Móvil'),
    ('Fundamentos de Desarrollo Web'),
    ('Fundamentos de Diseño Digital'),
    ('Fundamentos de Inteligencia Artificial'),
    ('Fundamentos de Software de Sistemas'),
    ('Geoaplicaciones Web y Móviles'),
    (
        'Geointeligencia Artificial Aplicada a la Teledetección'
    ),
    ('Gestión de Servidores y Seguridad'),
    ('Graficación por Computadora'),
    ('Herramientas de Software'),
    ('Ingeniería de Software'),
    ('Interacción de Redes'),
    ('Interfaces de Comunicaciones'),
    ('Interfaces Digitales de Comunicación'),
    ('Interfaces Gráficas con Aplicaciones'),
    ('Introducción a los Sistemas Geoespaciales'),
    ('Lenguajes de Programación'),
    ('Matemáticas Discretas I'),
    ('Matemáticas Discretas II'),
    ('Microcontroladores'),
    ('Modelado Matemático'),
    ('Modelado y Simulación de Redes'),
    ('Motores Gráficos'),
    ('Pensamiento Algorítmico'),
    ('Prácticas Profesionales COMP'),
    ('Prácticas Profesionales ISI'),
    ('Principios de Cómputo en la Nube'),
    ('Principios de Seguridad Informática'),
    ('Probabilidad y Estadística'),
    ('Procesamiento de Señales'),
    ('Programación de Robots'),
    ('Programación de Videojuegos'),
    ('Proyectos Computacionales I'),
    ('Proyectos Computacionales II'),
    ('Proyectos Computacionales III'),
    ('Representación del Conocimiento y Ontologías'),
    ('Robótica'),
    ('Robótica Inteligente'),
    ('Seminario de Medio Término'),
    ('Seminario de Orientación en Computación'),
    ('Servicios en la Nube'),
    ('Sistemas Embebidos'),
    ('Sistemas Interactivos'),
    ('Sistemas Operativos'),
    ('Sistemas Operativos Avanzados'),
    ('Supercómputo'),
    ('Tecnología Orientada a Objetos'),
    ('Temas Selectos de Matemáticas'),
    ('Temas Selectos de Videojuegos'),
    ('Visión Computacional')
ON CONFLICT ("tagName") DO NOTHING; -- Avoid duplicate tags if the migration is run multiple times

COMMIT;